### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IzzySoft** [AmkSk/homeberry#2]
What license is your project using? I assume GPL-3.0, like the "backend"?

**Comment by AmkSk** [comment]
Hello,
thanks for reminding me, I forgot to add LICENSE to the project. Yes, I
have used GPL 3.0 for the project. Do you mind asking me, how are you going
to use HomeBerry? I am just curious :)

AmkSk

**Comment by IzzySoft** [comment]
> thanks for reminding me, I forgot to add LICENSE to the project. Yes, I have used GPL 3.0 for the project.

Thanks for confirming – and adding!

> Do you mind asking me, how are you going to use HomeBerry? I am just curious :)

Not using it myself (I'm running BananaPis), but [making it easier accessible](https://apt.izzysoft.de/fdroid/index/apk/sk.amk.homeberry). So users can install it with the [F-Droid](https://f-droid.org/) client, which also will inform them about updates (my updater checks all 24h for new tags and, if found, fetches the attached APK).

PS: should you be interested in establishing [Fastlane structures](https://gitlab.com/snippets/1895688) in your repo, so you can maintain summary, description, screenshots etc and they'll also get fetched automatically, I can provide you a "starter package" with what I've set up here. And should you be interested in a listing with "F-Droid proper" (the big main repo), I can also help with that (fastlane would be helpful to have then).
